{
 "title": "eduVPN",
 "tags": [ "eduVPN" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "profiles",
    "label": "Profiles",
    "query": {
     "query": "label_values(eduvpn_active_connections,profile)"
    }
   },
   {
    "name": "vpn_protos",
    "label": "VPN Protos",
    "query": {
     "query": "label_values(eduvpn_active_connections,vpn_proto)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active connections",
   "type": "stat",
   "description": "Sum of active eduVPN connections across all profiles",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eduvpn_active_connections{vpn_proto=~\"${vpn_protos}\"}) by (vpn_proto)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eduvpn_max_connections{vpn_proto=~\"${vpn_protos}\"}) by (vpn_proto)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eduvpn_active_connections{vpn_proto=~\"${vpn_protos}\"}) by (vpn_proto) / sum(eduvpn_max_connections{vpn_proto=~\"${vpn_protos}\"}) by (vpn_proto)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique users",
   "type": "stat",
   "description": "Unique users with active connections",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eduvpn_unique_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active ${vpn_protos} connections by profile",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "repeat": "vpn_proto",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eduvpn_active_connections{vpn_proto=~\"${vpn_protos}\"}) by (profile)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated IPs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eduvpn_allocated_ips{vpn_proto=~\"${vpn_protos}\"}) by (vpn_proto)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free IPs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eduvpn_free_ips) by (vpn_proto)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eduvpn_allocated_ips) by (vpn_proto) / (sum(eduvpn_allocated_ips) by (vpn_proto) + sum(eduvpn_free_ips) by (vpn_proto))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Profile: $profiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "profiles" },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eduvpn_active_connections{profile=~\"${profiles}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eduvpn_max_connections{profile=~\"${profiles}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage ratio",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eduvpn_active_connections{profile=~\"${profiles}\"} / eduvpn_max_connections{profile=~\"${profiles}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated IPs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eduvpn_allocated_ips{profile=~\"${profiles}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free IPs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eduvpn_free_ips{profile=~\"${profiles}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eduvpn_allocated_ips{profile=~\"${profiles}\"} / (eduvpn_allocated_ips{profile=~\"${profiles}\"} + eduvpn_free_ips{profile=~\"${profiles}\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}